# PBS flags
queue: express
project: x77
walltime: 0:30:00
ncpus: 2
mem: 4GB
jobname: double_gyre
runspersub: 15

collate: false
collate_walltime: 0:30:00
collate_mem: 30GB
# Model config
model: mom6
# model: gold
shortpath: /short/v45
exe: MOM6
input: double_gyre
priority: 15
stacksize: unlimited 

runlog: true

