# PBS flags
queue: express
project: tm70
walltime: 0:30:00
ncpus: 4
mem: 8GB
jobname: double_gyre
runspersub: 10

collate: false
collate_walltime: 0:30:00
collate_mem: 30GB
# Model config
model: mom6
shortpath: /scratch/tm70
exe: /g/data/tm70/aph502/mom6-ninja-nci/ocean_only_symmetric/MOM6
input: /g/data/tm70/payu/mom6/double_gyre_orig/input
stacksize: unlimited 

runlog: true

# userscripts:
#     setup: runmpi4py.sh

manifest:
    fasthash: 
            - binhash
    fullhash: 
            - sha256
        # ignore: '*.nc'
    # reproduce:
        #     input: True
