# PBS flags
queue: express
project: x77
walltime: 0:30:00
ncpus: 64
mem: 128GB
jobname: double_gyre
runspersub: 10

collate: false
collate_walltime: 0:30:00
collate_mem: 30GB
# Model config
model: mom6
shortpath: /scratch/v45
exe: MOM6-25Jan2020
input: double_gyre
stacksize: unlimited 

runlog: true

# userscripts:
#     setup: runmpi4py.sh

manifest:
    fasthash: 
            - binhash
    fullhash: 
            - sha256
        # ignore: '*.nc'
    reproduce:
            input: True
