format: yamanifest
version: 1.0
---
work/INPUT/Depth_list.nc:
  fullpath: /scratch/v45/aph502/mom6/input/double_gyre/Depth_list.nc
  hashes:
    binhash: 0179c900f00163f6311d0df30637e72c
work/INPUT/Vertical_coordinate.nc:
  fullpath: /scratch/v45/aph502/mom6/input/double_gyre/Vertical_coordinate.nc
  hashes:
    binhash: 292ac911b54b9cab6e62a0147da4a098
work/INPUT/lalala:
  fullpath: /scratch/v45/aph502/mom6/input/double_gyre/lalala
  hashes:
    binhash: 6d4ba9e47b8d1e44a249868f630a3aa3
work/INPUT/ocean_geometry.nc:
  fullpath: /scratch/v45/aph502/mom6/input/double_gyre/ocean_geometry.nc
  hashes:
    binhash: bf6f4eba2ddc63edff2e55ad2f5f0aab
