format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /group/pawsey0410/aidanh/mom6/archive/mom6_double_gyre/restart013/MOM.res.nc
  hashes:
    binhash: 1dad60ac242f6115de417cb16f419c87
    md5: e027231d9524f0e1f23a5f7a0fedfeec
work/INPUT/MOM.res_Y0001_D141_S00000.nc:
  fullpath: /group/pawsey0410/aidanh/mom6/archive/mom6_double_gyre/restart013/MOM.res_Y0001_D141_S00000.nc
  hashes:
    binhash: 24e866255a0073daa8b9e2be130bee8b
    md5: 15a71ac1e4492b6fe943a945b4d9eeeb
work/INPUT/ocean_solo.res:
  fullpath: /group/pawsey0410/aidanh/mom6/archive/mom6_double_gyre/restart013/ocean_solo.res
  hashes:
    binhash: 957edb39d083265fe4fca6363c506896
    md5: 1e55ba1801b9a066f1c13eb054de0624
