format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre/restart003/MOM.res.nc
  hashes:
    binhash: feb6d7f8150fef265ba4840be6433f17
    md5: 79f4a40cf2c963aaf19735c36c60c489
work/INPUT/ocean_solo.res:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre/restart003/ocean_solo.res
  hashes:
    binhash: 3c8cf8a9d8c644dd2803ed8b6767773d
    md5: b45544138c824f96b3fea9be261fcf3d
