format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre/restart008/MOM.res.nc
  hashes:
    binhash: 9a264ad7427b278af5f213f219f6e3a3
    md5: 7066523a9a35c746f04ac58e7a1d67f5
work/INPUT/ocean_solo.res:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre/restart008/ocean_solo.res
  hashes:
    binhash: d00cdef5c6546e662a5bef31641cc89e
    md5: dbd4c2aaf88f346f7c174176a826ce92
