format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/v45/aph502/mom6/archive/double_gyre/restart019/MOM.res.nc
  hashes:
    binhash: 94dcb2e07900ee1dcadca3593db574cb
    md5: 4f0ed77ea550032cc266e2e5b55c1178
work/INPUT/MOM.res_Y0001_D201_S00000.nc:
  fullpath: /scratch/v45/aph502/mom6/archive/double_gyre/restart019/MOM.res_Y0001_D201_S00000.nc
  hashes:
    binhash: cbd8f8626a9fea9d56b3895bd0336cf2
    md5: 2e2c1919351a7d04f55d8e0e2fa86ff1
work/INPUT/ocean_solo.res:
  fullpath: /scratch/v45/aph502/mom6/archive/double_gyre/restart019/ocean_solo.res
  hashes:
    binhash: 20b78af669ea4e3cb4f4e9f34620cccc
    md5: 6fc68f2c3925c6f4b53beb966987965d
