format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre/restart011/MOM.res.nc
  hashes:
    binhash: 100d6e2b650a56e42cba38ca36d8fde5
    md5: 597492fcb33b7bafe362ff2c8d94f21b
work/INPUT/MOM.res_Y0001_D111_S00000.nc:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre/restart010/MOM.res_Y0001_D111_S00000.nc
  hashes:
    binhash: 53923b3d5dacdb0f4b3bd309f43e692c
    md5: 6fcbfd97ddd77c4caf5db300b130be12
work/INPUT/ocean_solo.res:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre/restart011/ocean_solo.res
  hashes:
    binhash: dc40925646abf2946f8de8ceb5efdf8c
    md5: 66f65e6c19941d5bbcebc1e69e84dc00
