format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /group/pawsey0410/aidanh/mom6/archive/mom6_double_gyre/restart022/MOM.res.nc
  hashes:
    binhash: 2ba2ee3e3e9bee63080e65c6dd881c02
    md5: f4b3d3f19a61a2c9462ecf89858a54af
work/INPUT/MOM.res_Y0001_D231_S00000.nc:
  fullpath: /group/pawsey0410/aidanh/mom6/archive/mom6_double_gyre/restart022/MOM.res_Y0001_D231_S00000.nc
  hashes:
    binhash: 343c7926f6b9aeef62e4d0fca414dc96
    md5: 94d70b7019e8cbd2be7039f9e6f9c482
work/INPUT/ocean_solo.res:
  fullpath: /group/pawsey0410/aidanh/mom6/archive/mom6_double_gyre/restart022/ocean_solo.res
  hashes:
    binhash: 3efd54657b410216bc9df8a930c475c1
    md5: dfb35fe324e99134626a005760e505d1
