format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre/restart001/MOM.res.nc
  hashes:
    binhash: f147cc15bbb10dea46b04287c34fef63
    md5: e57d713f6f7483e3f186d6649995a2a2
work/INPUT/ocean_solo.res:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre/restart001/ocean_solo.res
  hashes:
    binhash: bb1e6315caee5a29695a7f1b3905bec7
    md5: 5b3e964cc60bbc5a3a4e894c451265c1
