format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /group/pawsey0410/aidanh/mom6/archive/mom6_double_gyre/restart016/MOM.res.nc
  hashes:
    binhash: d8d40ff41bbc84fa841bbdf461aaa2f2
    md5: cee10662920c0b2f095fe47b53bcae3d
work/INPUT/MOM.res_Y0001_D171_S00000.nc:
  fullpath: /group/pawsey0410/aidanh/mom6/archive/mom6_double_gyre/restart016/MOM.res_Y0001_D171_S00000.nc
  hashes:
    binhash: 33115c0e1c80cc69775016bf61364cc4
    md5: b426569d2ea930a8e3c0c6d0f1089f55
work/INPUT/ocean_solo.res:
  fullpath: /group/pawsey0410/aidanh/mom6/archive/mom6_double_gyre/restart016/ocean_solo.res
  hashes:
    binhash: 4fff398b7beaeeef852ee5d1605943a8
    md5: 0757a8e6225ff0c1ec5a20a2ab389faf
