format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/v45/aph502/mom6/archive/double_gyre/restart083/MOM.res.nc
  hashes:
    binhash: 88a341577b16eecd74bfc07af564a5ce
    md5: f5dd0a2a9e74b9295ec0b68e844879ac
work/INPUT/MOM.res_Y0003_D111_S00000.nc:
  fullpath: /scratch/v45/aph502/mom6/archive/double_gyre/restart083/MOM.res_Y0003_D111_S00000.nc
  hashes:
    binhash: a4ccb1549c2a021918fecad928e15b8a
    md5: 4ae39204858a6fd003b005f6f5b56d34
work/INPUT/ocean_solo.res:
  fullpath: /scratch/v45/aph502/mom6/archive/double_gyre/restart083/ocean_solo.res
  hashes:
    binhash: b6b1a31513d9062c6ec2380c2984b2a6
    md5: c9b7dca40df6d5017cbaacaeb6cad2a0
