format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/v45/aph502/mom6/archive/double_gyre/restart064/MOM.res.nc
  hashes:
    binhash: 286bde6cac8297b28b1dcb30fb7a5d41
    md5: e48621169ed2c63507ee7dfc0977d61c
work/INPUT/MOM.res_Y0002_D286_S00000.nc:
  fullpath: /scratch/v45/aph502/mom6/archive/double_gyre/restart064/MOM.res_Y0002_D286_S00000.nc
  hashes:
    binhash: 77e05d635e02392b57d4d348b675daaa
    md5: c6ee69d2329b7686be3b741f3a892df0
work/INPUT/ocean_solo.res:
  fullpath: /scratch/v45/aph502/mom6/archive/double_gyre/restart064/ocean_solo.res
  hashes:
    binhash: e26c7be5767ac6ff2cc0c0e4529cd0c8
    md5: bb14fdb2cd52cb2f1d5fa47cc1175719
