format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/v45/aph502/mom6/archive/double_gyre/restart010/MOM.res.nc
  hashes:
    binhash: 700221cfc491f42c78df8eb7b59c2050
    md5: accfae1d4e3cb8664bcacf66ee55e8fc
work/INPUT/MOM.res_Y0001_D111_S00000.nc:
  fullpath: /scratch/v45/aph502/mom6/archive/double_gyre/restart010/MOM.res_Y0001_D111_S00000.nc
  hashes:
    binhash: a4191d037065452c2e6234d38f99abc3
    md5: b621093257a751f11e7b13b13cf2fcc0
work/INPUT/ocean_solo.res:
  fullpath: /scratch/v45/aph502/mom6/archive/double_gyre/restart010/ocean_solo.res
  hashes:
    binhash: 8ddf5e393af8b13d911eb313d366d65a
    md5: c5f49ca2e5ae7f854efac1123206cbb5
