format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /group/pawsey0410/aidanh/mom6/archive/mom6_double_gyre/restart010/MOM.res.nc
  hashes:
    binhash: 5a37f7e3b214e36c71b0f3f8047fcdc2
    md5: 90178694ae804348637319a63dea90a8
work/INPUT/MOM.res_Y0001_D111_S00000.nc:
  fullpath: /group/pawsey0410/aidanh/mom6/archive/mom6_double_gyre/restart010/MOM.res_Y0001_D111_S00000.nc
  hashes:
    binhash: 63318ae93f1b3e1c35384c3ef6adcabe
    md5: 6a5320f4e98e213a1eeb26c5fcd5b8d5
work/INPUT/ocean_solo.res:
  fullpath: /group/pawsey0410/aidanh/mom6/archive/mom6_double_gyre/restart010/ocean_solo.res
  hashes:
    binhash: 4e7d12525e11b65c66aa0c95876058ec
    md5: c5f49ca2e5ae7f854efac1123206cbb5
