format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre/restart014/MOM.res.nc
  hashes:
    binhash: e5744ada8dbcf2f706d9f666d01d546d
    md5: b5e59e4b68d654df609b7a0d86323ddb
work/INPUT/ocean_solo.res:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre/restart014/ocean_solo.res
  hashes:
    binhash: 6afd0d5ac1a72da975fbb6305ea8af20
    md5: f8833808f5cf95dc8bc3ec17c1422e13
